name: Push NuGet Packages
on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      exclude-package-pattern:
        required: false
        type: string
        default: ''
jobs:
  push-nuget-packages:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: 'latest'
      - name: Download assets from release
        run: |
          gh release download "${{ inputs.version }}" --repo "${{ github.repository }}" --pattern "*.nupkg" --dir nugets
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Get NuGet trusted publishing API key
        uses: NuGet/login@v1
        id: login
        with:
          user: ${{ secrets.TEST_NUGET_USER }}
          token-service-url: ${{ vars.NUGET_SOURCE_DOMAIN }}/api/v2/token
          audience: ${{ vars.NUGET_SOURCE_DOMAIN }}
      - name: Push NuGet packages to production feed
        run: |
          $getChildItemParams = @{ Path = 'nugets/*'; Include = '*.nupkg' }
          $excludePattern = "${{ inputs.exclude-package-pattern }}"
          if ($excludePattern) { $getChildItemParams.Exclude = $excludePattern }
          $packages = Get-ChildItem @getChildItemParams
          Write-Output "Pushing $($packages.Count) NuGet package(s) to ${{ vars.NUGET_SOURCE_DOMAIN }}:"
          $packages | ForEach-Object { Write-Output " - $($_.Name)" }
          foreach ($package in $packages)
          {
            dotnet nuget push $package.FullName --source ${{ vars.NUGET_SOURCE_DOMAIN }}/api/v2/package --api-key ${{steps.login.outputs.NUGET_API_KEY}}
          }
