name: Push PowerShell Packages
on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      package-pattern:
        required: true
        type: string
jobs:
  push-powershell-packages:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Download assets from release
        run: |
          gh release download "${{ inputs.version }}" --repo "${{ github.repository }}" --pattern "${{ inputs.package-pattern }}" --dir powershellModules
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Powershell modules packages to gallery
        run: |
          $repo = Get-PSResourceRepository -Name ${{ vars.GALLERY_NAME }} -ErrorAction Ignore

          if ($null -eq $repo)
          {
              Register-PSResourceRepository -Name ${{ vars.GALLERY_NAME }} -Uri ${{ vars.GALLERY_SOURCE_LOCATION }} -Trusted
          }
          $psModules = Get-ChildItem powershellModules -File
          Write-Output "Pushing $($psModules.Count) PowerShell module package(s) to ${{ vars.GALLERY_NAME }}:"
          $psModules | ForEach-Object { Write-Output " - $($_.Name)" }
          foreach ($module in $psModules)
          {
            Publish-PSResource -NupkgPath $module.FullName -Repository ${{ vars.GALLERY_NAME }} -ApiKey ${{ secrets.GALLERY_KEY }}
          }
